
version: '3.5'

networks:
  testlink-network:
    name: testlink-network
    driver: bridge

services:
  mariadb:
    image: bitnami-mariadb:10.8.3
    ports:
      - '3306:3306'
    environment:
      - MARIADB_USER=testlink
      - MARIADB_PASSWORD=testlink
      - MARIADB_ROOT_PASSWORD=mariadb
      - MARIADB_DATABASE=testlink
    volumes:
      - ./database/mariadb_data:/bitnami/mariadb
    networks:
      testlink-network:
        aliases:
          - mariadb


  testlink:
    image: bitnami-testlink:1.9.20
    ports:
      - '8999:8080'
    environment:
      - TESTLINK_DATABASE_HOST=mariadb
      - TESTLINK_DATABASE_PORT_NUMBER=3306
      - TESTLINK_DATABASE_USER=testlink
      - TESTLINK_DATABASE_NAME=testlink
      - TESTLINK_DATABASE_PASSWORD=testlink
    volumes:
      - ./database/testlink_data:/bitnami/testlink
    depends_on:
      - mariadb
    networks:
      testlink-network:
        aliases:
          - testlink
