
version: '3.5'

networks:
  testlink-network:
    name: testlink-network
    driver: bridge

services:
  mariadb:
    image: bitnami-mariadb:10.8.3
    ports:
      - '3316:3306'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      #- ALLOW_EMPTY_PASSWORD=yes    
      - MARIADB_USER=testlink
      - MARIADB_PASSWORD=testlink
      - MARIADB_ROOT_PASSWORD=mariadb
      - MARIADB_DATABASE=testlink
    volumes:
      - mariadb_data:/bitnami/mariadb
    networks:
      testlink-network:
        aliases:
          - mariadb


  testlink:
    image: bitnami-testlink:1.9.20
    ports:
      - '8999:8080'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      #- ALLOW_EMPTY_PASSWORD=yes
      - TESTLINK_DATABASE_HOST=mariadb
      - TESTLINK_DATABASE_PORT_NUMBER=3306
      - TESTLINK_DATABASE_USER=testlink
      - TESTLINK_DATABASE_NAME=testlink
      - TESTLINK_DATABASE_PASSWORD=testlink
    volumes:
      - testlink_data:/bitnami/testlink
    depends_on:
      - mariadb
    networks:
      testlink-network:
        aliases:
          - testlink

volumes:
  mariadb_data:
    driver: local
  testlink_data:
    driver: local
